A function f is defined by $$ f(x) = \begin{cases} 1-x, & \text{if $x \le -1$} \\ x^2, & \text{if $x \gt -1$} \end{cases} $$

In this case we need to pass a linspace to the piecewise function definition and redefine each time we redefine x

In [3]:
from numpy import *
from sympy import *

In [4]:
x = linspace(-2, -2, 1)

In [5]:
fx = piecewise(x, [x <= -1, x > -1], [lambda x: 1 - x, lambda x: x**2])

In [6]:
fx

array([ 3.])

In [7]:
x = linspace(-1, -1, 1)

In [8]:
fx = piecewise(x, [x <= -1, x > -1], [lambda x: 1 - x, lambda x: x**2])

In [9]:
fx

array([ 2.])

In [10]:
x = linspace(0, 0, 1)

In [11]:
fx = piecewise(x, [x <= -1, x > -1], [lambda x: 1 - x, lambda x: x**2])

In [12]:
fx

array([ 0.])

Can't get python to plot it =(